### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by PianSom** [pacemaker82/PredBat-Table-Card#1]
Nice work - thanks!

Given that each row is on two text lines (because the the day/time), it may be nicer to have the import/export costs on two lines also - save having such wide cols.

But only a small suggestion - feel free to ignore.

![Screenshot 2024-02-27 at 13 06 09](https://github.com/pacemaker82/PredBat-Table-Card/assets/25636191/81b740d2-2441-49b8-892e-613b0e0f246d)

(Obvs this is for Expert mode, where the post-inefficiency costs are shown.)

**Comment by pacemaker82** [comment]
I'll have a look at these column widths first, they shouldnt appear so wide honestly (but yeah expert mode, I hadnt considered...) will have a ponder

**Comment by pacemaker82** [comment]
Added support for it in v 1.0.2 https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.0.2
