### ISSUE TITLE
Light/Dark scheme Switching

### ISSUE THREAD

**Issue by Dave-Parry** [pacemaker82/PredBat-Table-Card#11]
My HA scheme is set to dark but the card is staying on light scheme.
Have tried reloading the card
As requested here is my yaml for my card.

type: custom:predbat-table-card
entity: predbat.plan_html
columns:
  - time-column
  - import-export-column
  - state-column
  - limit-column
  - pv-column
  - load-column
  - soc-column
  - cost-column
  - total-column
odd_row_colour: '#181f2a'
even_row_colour: '#2a3240'
table_width: 100

**Comment by pacemaker82** [comment]
Thanks - Would you add the following YAML config:

light_mode: auto

or 

light_mode: dark

It should work without it, but want to see if that at least works. Can you also tell me what your profile is set to (goto your username, then scroll down, it will be set to auto, light or dark). thanks

**Comment by Dave-Parry** [comment]
Tried both and neither worked, but have found out its my profile theme setting.
I had it set to a theme called “darkish”. Changing this to default cured the problem.
I use the darkish theme because I wanted the background to be Black with no borders,  and couldn’t find the setting to achieve this in the default theme.
Will have another poke around to see if I can find the setting to change background colour in the default theme config.

Regards
Dave. P.
***@***.***

**Comment by pacemaker82** [comment]
ah ok - yeah my code is looking to see if dark mode is enabled in the hass object (hass.theme.darkMode) - so presume the theme you are using doesnt have that variable so my code is breaking. I will see how I can work around that (if not present, take the card YAML explicitly)

**Comment by pacemaker82** [comment]
I just triple checked my code against your use case and it should strictly prioritise the card YAML if you have set it correctly.

`light_mode: dark`

Just want to triple check you set it correctly before I keep digging.

**Comment by pacemaker82** [comment]
going to close this out as without any more info I am not sure what else to do. please re-open if you have something else to add - many thnaks
