### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by dandwhelan** [pacemaker82/PredBat-Table-Card#12]
Hey,
I've no idea why but my load kws says Nan since this morning after a reboot of HA
![Screenshot_20240304_134151_Home Assistant](https://github.com/pacemaker82/PredBat-Table-Card/assets/79152287/54b9470b-a38c-449a-9033-3e84586430bd)
![Screenshot_20240304_134200_Home Assistant](https://github.com/pacemaker82/PredBat-Table-Card/assets/79152287/cb10547b-6b49-4022-9ae8-50d91d3c37af)
type: custom:predbat-table-card
entity: predbat.plan_html
columns:
  - time-column
  - import-column
  - state-column
  - pv-column
  - car-column
  - load-column
  - soc-column
  - cost-column
  - total-column
odd_row_colour: '#181f2a'
even_row_colour: '#2a3240'
fill_empty_cells: true
light_mode: auto
debug_prices_only: true

**Comment by pacemaker82** [comment]
Hmm something is very messed up here. Do me a favour, first can you upgrade to 1.2.1 which is out now? You can force update through HACS, goto the card in HACS library and use the 3 dot menu in the top right to download latest. I'll have a look with your config on mine.

**Comment by dandwhelan** [comment]
Sorry forgot to mention. I'm on the latest version. 1.21

**Comment by pacemaker82** [comment]
ah I have seen the issue - iBoost column - I am not supporting that yet - which reminds me to support it :) 

I'll sort it out in the next couple of hours. Please hold...

**Comment by dandwhelan** [comment]
No rush, it's not urgent at all. Good spot on the iboost

**Comment by pacemaker82** [comment]
Just pushed 1.2.2 out, it was a quick fix. Should work now, let me know

**Comment by dandwhelan** [comment]
Thanks, that's working.
