### ISSUE TITLE
Minor: formatting of negative import rates isn't correct

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#14]
First time we've had negative agile rates I think, the card doesn't format them correctly:

Predbat HTML:
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/d5f6aa57-4c8b-469d-8481-0c837a68aeb2)

Predbat table card:
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/5a54efe1-2e53-4444-a9f2-8d9f5bafab15)

The actual import price appears with two minus's afterwards,  the effective import price loses the minus sign completely

**Comment by pacemaker82** [comment]
Could you try new release 1.5.1.3 https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.1.3 - I am hoping it resolves it.

**Comment by pacemaker82** [comment]
Should be back in business with [1.5.1.4](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.1.4)

**Comment by gcoan** [comment]
This all looks fine thank you
