### ISSUE TITLE
Overlapping of friendly states

### ISSUE THREAD

**Issue by SwiftRR** [pacemaker82/PredBat-Table-Card#16]
I like your plan and am trying out your 'friendly states'. 
The only hiccup is where there are 2 states in the same block, e.g.
<img width="652" alt="Screenshot 2024-04-08 at 09 04 32" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/68816364/8fafb493-82e4-4f83-8ffe-b142f75eb86c">
Could the unfriendly states be used just for the overlap situation, as in normal plan?, e.g.
<img width="150" alt="image" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/68816364/3d195470-0c8c-407d-9233-d612b5c6a33e">

Thanks

Rob

**Comment by pacemaker82** [comment]
Thanks - yeah I'll take a look into this. Can you share your card YAML so I can replicate your card locally?

**Comment by pacemaker82** [comment]
Please also make sure you're on the latest version. There was a bug with this a few weeks ago which was resolved. 

Goto HACS, goto the card, and "re-download" I think - or HA settings > check for updates.

Here's how it looks for me if I crush the columns as close as possible:
<img width="501" alt="Screenshot 2024-04-08 at 09 27 29" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/679cdabd-6fd0-4c0f-a188-159ed36914f5">

**Comment by pacemaker82** [comment]
Here's how to update in HACS:
<img width="671" alt="Screenshot 2024-04-08 at 09 30 14" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/e6907659-0075-45c9-9e29-6db329962349">

**Comment by pacemaker82** [comment]
Yeah it looks like you're on the old version. Please update per instructions above ^

Here's your card running for me on the latest version:
<img width="750" alt="Screenshot 2024-04-08 at 09 33 35" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/c01476ad-f8c1-461f-bbc9-db1cf6b7914f">

**Comment by SwiftRR** [comment]
Thanks. I beat you to the update and I think you have fixed this already.
This is my latest view for 2 states in a slot:
<img width="744" alt="image" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/68816364/c6afdb1a-18dc-41d8-ade7-c5fb841d40cc">

**Comment by SwiftRR** [comment]
Thanks. I have closed.
I like your card, especially the flexibility to change the order of the columns.

Rob
