### ISSUE TITLE
Align text - PLEASE

### ISSUE THREAD

**Issue by PianSom** [pacemaker82/PredBat-Table-Card#2]
Just playing with the col order. And the PV and Load text do not align. (Presumably because of the sun symbol.)

Makes me want to cry.

![Screenshot 2024-02-27 at 13 19 07](https://github.com/pacemaker82/PredBat-Table-Card/assets/25636191/cf9b8019-f127-41a4-9722-a2f642124aa3)

**Comment by pacemaker82** [comment]
yeah this is caused by the sun icon - will see what i can do

**Comment by pacemaker82** [comment]
this looks better? 

<img width="466" alt="Screenshot 2024-02-27 at 14 28 39" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/25c07592-cf76-437a-91da-533f22531c39">

**Comment by pacemaker82** [comment]
Closing. Fixed in 1.0.1. Should be able to update from HACS or you'll get a notification at some point
