### ISSUE TITLE
In-correct columns

### ISSUE THREAD

**Issue by godfreym29** [pacemaker82/PredBat-Table-Card#20]
I've added the custom repository and downloaded the card.
Used the default config from github, but the columns appear to displaying incorrectly
I've uploaded a screenshot of the problem.

This is the config that was used:

`
type: custom:predbat-table-card
entity: predbat.plan_html
columns:
  - time-column
  - import-column
  - export-column
  - state-column
  - limit-column
  - pv-column
  - load-column
  - soc-column
  - cost-column
  - total-column
table_width: 100
fill_empty_cells: true
`

![Capture](https://github.com/pacemaker82/PredBat-Table-Card/assets/78360791/cf5efae4-42f1-4079-8381-1ef1f2a68d1e)

**Comment by pacemaker82** [comment]
are you using any custom templates in home assistant?

**Comment by godfreym29** [comment]
Yes
I’ve been using HA for a few years now, so have quite a few templates for sensor and also in mushroom template cards

**Comment by pacemaker82** [comment]
sorry I meant custom themes. Any installed? 

Are there any other cards on that page? Can you try putting the card on a single page to rule out other card interference?

**Comment by godfreym29** [comment]
No, no custom themes.
Tried both a new page and a new dashboard, still get the same result

**Comment by godfreym29** [comment]
Hope this is enough

![Capture](https://github.com/pacemaker82/PredBat-Table-Card/assets/78360791/eac5c34f-5018-4651-b1df-d738d381ff08)
![Capture2](https://github.com/pacemaker82/PredBat-Table-Card/assets/78360791/65420142-87b0-425c-b3ec-24841a9b18fe)

**Comment by pacemaker82** [comment]
Ah its the new CO2 columns. I will add support for those and reply here once uploaded.

**Comment by pacemaker82** [comment]
Please goto HACS and redownload the card. Version https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3 should add support.

**Comment by godfreym29** [comment]
All looking go now .
Thank you - much appreciated.

![Capture](https://github.com/pacemaker82/PredBat-Table-Card/assets/78360791/a2bd898a-8746-4e1f-85a2-9d5c1cac5feb)

**Comment by pacemaker82** [comment]
Excellent - thanks for bringing it up and reminding me!
