### ISSUE TITLE
Can't load plan on v7.17.5

### ISSUE THREAD

**Issue by bensebborn** [pacemaker82/PredBat-Table-Card#21]
Getting error: 

![IMG_6096](https://github.com/pacemaker82/PredBat-Table-Card/assets/160988/4b29bd61-db6a-4fda-b16b-d83b0941f481)

Normal plan is loading ok on the default html view

**Comment by pacemaker82** [comment]
This error is related to extracting the "last updated" time from the original predbat card. This was changed in Predbat 7.17 onwards

Did you update the card to latest version which fixes this?
