### ISSUE TITLE
State icons missing

### ISSUE THREAD

**Issue by nickgee31** [pacemaker82/PredBat-Table-Card#22]
There seems to be an issue with one of the recent updates. The icons are missing for charging and discharging, only the idle and when there is charging and discharging in the same slot does it show: 

<img width="489" alt="Screenshot 2024-04-27 at 15 28 41" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/110033252/86214be0-ef5b-4c87-b483-9c98bf7ca88c">

Here's the code I am using: 

type: custom:predbat-table-card
entity: predbat.plan_html
columns:
  - time-column
  - import-export-column
  - state-column
  - pv-column
  - load-column
  - car-column
  - soc-column
  - cost-column
  - total-column
hide_empty_columns: true
light_mode: auto

I've managed to workaround out by using the old skool state column so no major issue.

**Comment by pacemaker82** [comment]
Thanks - Fixed in the next update coming later today.

**Comment by pacemaker82** [comment]
Fixed in https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.1
