### ISSUE TITLE
Repository structure for v1.5.3.1 is not compliant

### ISSUE THREAD

**Issue by laurence600** [pacemaker82/PredBat-Table-Card#23]
Getting this error when trying to add to HACs

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/162343223/6a7def8a-3bc5-434b-a19b-b1c722e38f00)

**Comment by pacemaker82** [comment]
type should be `lovelace`

<img width="382" alt="Screenshot 2024-04-29 at 19 07 44" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/9aea2604-cb53-4cd8-8739-b925405d92ee">

**Comment by pacemaker82** [comment]
Have updated the readme install instructions to make the `Lovelace` type clear.
