### ISSUE TITLE
Idle status in the plan showing as Charge/Discharge since recent HTML update

### ISSUE THREAD

**Issue by RobinCu** [pacemaker82/PredBat-Table-Card#25]
Since Trefor updated the HTML, in a single slot that includes Idle and Discharge, the plan shows Charge/Discharge (example below in 21:30 slot).

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/139381810/113e4fd0-fd1e-4efe-adc6-c44063e0d488)

Whereas the battery chart and log shows idle 21:30-21:40 and the discharge 21:40 onwards.

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/139381810/db8b5c9e-d84b-4932-b2fc-7d73fc25864b)

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/139381810/38642241-8f81-4b6f-9dc8-f37f63e63314)

**Comment by PianSom** [comment]
Just to add ...

Here is my plan from 10pm tonight. Note that the Dashboard shows a charge at 22.30, whereas the original does not. They both show a charge at 02.30.

<img width="721" alt="Screenshot 2024-05-07 at 08 40 13" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/25636191/01260dcd-cb19-49d4-89a0-63e93e5e7375">
<img width="617" alt="Screenshot 2024-05-07 at 08 40 33" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/25636191/41376373-ccf9-4d35-a28f-b19b44ca7115">

**Comment by pacemaker82** [comment]
Thanks - am taking a look into this.

**Comment by pacemaker82** [comment]
Fixed in [1.5.3.3](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.3)

**Comment by pacemaker82** [comment]
scrap that, I didnt realise its also not just idle its charge and discharge - so thats fixed in 

https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.4

**Comment by RobinCu** [comment]
Fixed for me with idle/discharge and charge/discharge slots.
