### ISSUE TITLE
Charge Discharge Slots

### ISSUE THREAD

**Issue by charlie-chester** [pacemaker82/PredBat-Table-Card#27]
Predbat changed recently where sometimes it plans an Idol / Discharge in the same 30 minute slot.

Predbat Table Card shows this as a Charge / Discharge though.

Only easy to spot if you compare with the usual Predbat Plan. 

By the way this is just a brilliant piece of work.

**Comment by RobinCu** [comment]
Hi Charlie, 
This should have been fixed in https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.4.  Perhaps you need to update?
Robin

**Comment by charlie-chester** [comment]
I'm on 1.5.3.6 and still getting it.

**Comment by pacemaker82** [comment]
@charlie-chester could you post an example screenshot from both this card and the original predbat card? thx

**Comment by charlie-chester** [comment]
I've just forced a re download and it's now worked although I was definitely on .6. Maybe something hadn't quite updated. Did it before I saw you ask for screenshots!!

I noticed a couple on Facebook also reporting to Predbat that it was charging when it shouldn't so maybe a few others have the same issue. 

The only thing I would say now is that in the idle slot it now says Charge with an arrow up but not in green. Maybe just the arrow up like other idle slots might be a better representation. 

Just a thought. 

I'm also using old skool columns.

**Comment by charlie-chester** [comment]
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/0e89321c-d1ac-4015-8931-f69f11b5bced)

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/133705626/a7d7f565-cbf2-4679-8cc8-2213605066b7)

**Comment by pacemaker82** [comment]
@charlie-chester thanks for update.

Check out the read me about the friendly states: https://github.com/pacemaker82/PredBat-Table-Card/blob/main/README.md

I am adding to the arrows up down and "right" "Charging" "Discharging" and "Idle" for the "right" arrow.

I am not adding a colour background because Trefor's plan doesnt either. He highlights with colour when Predbat is doing something. So where you see no colour background, that just means the battery is behaving as normal without predbat.

**Comment by pacemaker82** [comment]
Just reflecting what I explained in your screenshots:

<img width="294" alt="Screenshot 2024-05-13 at 10 34 39" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/9a88d659-d185-4663-bca1-bcc531120036">

<img width="321" alt="Screenshot 2024-05-13 at 10 34 44" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/f1878260-a725-48e4-962d-01a6395cecf3">

**Comment by charlie-chester** [comment]
Yes it was green before I forced the update so it's working now. 

I just commented that maybe didn't need the Chg next to the arrow as it was an idle slot but that was just my opinion that's all. Now it's not green I can see the difference and know what it's doing. 

Don't know why I needed to force a re download but it's fixed now thanks. 

Again well done it's brilliant.
