### ISSUE TITLE
Predbat Update - V8.1.0 - Table Plan not loading, Variables on html plan

### ISSUE THREAD

**Issue by robyholmes** [pacemaker82/PredBat-Table-Card#31]
Since updating to Predbat V8.1.0 this evening, the Table Plan will no longer load and blocks other content on the dashboard loading. Refreshing on a PC browser seems to get past it so other content loads, and you can edit the dashboard. But the mobile app doesn't load anything at all if the Table Plan is present on the page.

I'm guessing this is due to the Prebat plan including some variables at the top of the HTML plan itself.
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/28155240/aa30d20c-b727-4955-83a2-feef1cda3e71)

Console shows the following when loading a dashboard with just the Table Plan Card on.
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/28155240/7db2be4b-432d-4ccb-97a3-4071ebff31b2)

Table Plan Card: v1.5.4
Predbat (Non-AppDemon, Add-on Driven): 8.1.0

**Comment by Dave-Parry** [comment]
Me too.

**Comment by pacemaker82** [comment]
am working on a fix now

**Comment by pacemaker82** [comment]
It seems the old way on 8.1.0 doesnt have these header variables... are these just on the new "add on" version of predbat?

**Comment by pacemaker82** [comment]
nevermind they appeared now, seemed to take a few refreshes of the plan for them to appear.

**Comment by pacemaker82** [comment]
FIXED in https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.5
