### ISSUE TITLE
Latest update is not showing the Import tariffs and columns are not aligned

### ISSUE THREAD

**Issue by Redding43** [pacemaker82/PredBat-Table-Card#32]
Just updated the latest version

Have tried on both ipad and laptop, the Import column is grey, have tried changing the theme but with no luck. Looks like the columns and values are not aligned either

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/122637671/99af0537-0f0e-45f9-9327-af29eba63737)

**Comment by Redding43** [comment]
Here you go

type: custom:predbat-table-card
entity: predbat.plan_html
columns:
  - time-column
  - import-column
  - car-column
  - state-column
  - limit-column
  - pv-column
  - load-column
  - soc-column
  - cost-column
  - total-column
table_width: 100
fill_empty_cells: true

**Comment by Redding43** [comment]
Also Dashboard Config, if it helps

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/122637671/921139db-1f8d-4ce0-aa08-4ddbb8069d10)

**Comment by Timeflies1980** [comment]
Yes I'm getting a similar issue where the columns are not matching  with the headings.

![Untitled](https://github.com/pacemaker82/PredBat-Table-Card/assets/170317240/5baefe0f-f6ac-4af1-91d1-c0db007f092f)

Config here:- 

type: custom:predbat-table-card
entity: predbat.plan_html
use_friendly_states: true
columns:
  - time-column
  - state-column
  - soc-column
  - limit-column
  - pv-column
  - load-column
  - car-column
  - cost-column
  - total-column
table_width: 100
fill_empty_cells: true
old_skool_columns:
  - soc-column
  - pv-column
  - load-column
  - state-column
hide_empty_columns: true

**Comment by pacemaker82** [comment]
Please can you test https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.5.2

I found an additional bug introduced by 8.1.0 release which should now be resolved.

**Comment by Timeflies1980** [comment]
> Please can you test https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.5.2
> 
> I found an additional bug introduced by 8.1.0 release which should now be resolved.

Perfect, That seems to have fixed it! Many thanks for all your work :-)

**Comment by Redding43** [comment]
Looking good, thanks!

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/122637671/df3ce3b7-c3ac-45f5-9dd6-5ef453bd8d71)

**Comment by gcoan** [comment]
latest version works fine on predbat 8.0.0 as well
