### ISSUE TITLE
Plan broken on Predate v8.1.1

### ISSUE THREAD

**Issue by Bighton** [pacemaker82/PredBat-Table-Card#33]
I've updated from Predate v8.0.0 to v8.1.1 and now the Table Card does not load giving the error as below
![Screenshot 2024-06-25 at 19 33 19](https://github.com/pacemaker82/PredBat-Table-Card/assets/146489048/fb76f1f8-2081-4682-b15a-5b2b52a78876)

**Comment by pacemaker82** [comment]
Please update to latest card version, this is fixed.

**Comment by Bighton** [comment]
Thanks for your quick reply.

Sorry to be a pain but update just hung after several attempts. I therefore thought that I'd better start from scratch and deleted the custom repository and the files at '/config/www/community/PredBat-Table-Card'. Unfortunately the download is now failing as below.

Am I doing something stupid?

![Screenshot 2024-06-25 at 22 25 56](https://github.com/pacemaker82/PredBat-Table-Card/assets/146489048/580de1e2-3bf1-4341-a9ae-d44a6c5fad1a)

**Comment by pacemaker82** [comment]
Hmmmm, seems like you might have deleted something important for HACS maybe? If I goto HACS, add custom repository, hit download, I get these screens:

<img width="593" alt="Screenshot 2024-06-26 at 10 55 21" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/23a254b8-ee30-4775-8f5b-feb87d891b84">

which downloads successfully and asks me to refresh:

<img width="562" alt="Screenshot 2024-06-26 at 10 55 36" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/8da05759-c184-4bce-a541-fca1ef058ce0">

You might try removing it from HACS and starting again:
<img width="525" alt="Screenshot 2024-06-26 at 10 57 14" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/9c6b5892-549a-4373-88da-071b720e6659">
