### ISSUE TITLE
Discharge not truncated properly on narrow screen alongside eco charge

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#34]
Plan for overnight shows three split charfe/discharge slots

First one at 4:30 looks fine in the plan but the 7:00 and 8:30 the word Discharge isn't truncated properly 

Landscape 
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/6f60dfac-32ad-4270-83d6-37515d977d03)

and portrait 
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/6232ac78-7dbb-4088-bde7-31abc23dc8c7)

Looking at the predbat plan it looks like the 4:30 is an active grid charge not a solar charge and that may be the cause of the issue 
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/34615e03-48cf-457e-a2c4-b7047dcde3e8)

**Comment by pacemaker82** [comment]
I'm chasing this one down, waiting for the situation where I have a solar charge, then a predbat discharge in the same window. This is the case where it goes funky - but on my end I dont get this situation that often.

**Comment by pacemaker82** [comment]
Should now be [fixed and available in 1.5.5.5](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.5.5)

Managed to find a way to dummy the data and test it out. Looks ok my end but please confirm.

**Comment by gcoan** [comment]
I'm on 1.5.5.4 at the moment so I won't upgrade and will wait to see it happening again so I can then try the fix

Thanks, it wasn't a high priority
