### ISSUE TITLE
Missing the first row of the predbat plan

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#36]
Its 00:50 and the predbat table card has omitted the first line of the predbat plan.

Never seen it done anything like this before !

Latest table card, 1.5.5.2
Predbat v8.0.0

Predbat plan:
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/fc3f8f19-adae-4705-8a9f-fb0d6bb81706)

Table card:
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/19b243b4-acf3-420d-ac78-bf3e1c35b2d0)

predbat_plan HTML:
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/d5bf6438-2b29-409e-86d2-62b01f969120)

copy/pasted:

html: <table><tr><td colspan=10> Plan starts: 2024-07-06 00:55 last updated: 00:55:00 version: v8.0.0</td></tr><tr><td><b>Time</b></td><td><b>Import p (w/loss)</b></td><td><b>Export p (w/loss)</b></td><td><b>State</b></td><td></td><td><b>Limit %</b></td><td><b>PV kWh (10%)</b></td><td><b>Load kWh (10%)</b></td><td><b>SOC %</b></td><td><b>Cost</b></td><td><b>Total</b></td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 00:55</td><td bgcolor=#FFFFAA>16.54 (18.23) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#AAFFAA>0.05 (0.07)</td><td bgcolor=#3AEE85>62&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>£0.00</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 01:00</td><td bgcolor=#FFFFAA>17.72 (19.53) </td><td bgcolor=#FFFFFF><b>15.00 (13.68)</b> </td><td colspan=2 bgcolor=#FFFF00>Dis&searr; &#8526;</td><td bgcolor=#FFFFFF> 36</td><td bgcolor=#BCBCBC></td><td bgcolor=#FFFF00>0.45 (0.52)</td><td bgcolor=#3AEE85>62&searr;</td><td bgcolor=#3AEE85>-32 p  &searr;</td><td bgcolor=#FFFFFF>£0.00</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 01:30</td><td bgcolor=#FFFFAA>18.22 (20.08) </td><td bgcolor=#FFFFFF><b>15.00 (13.68)</b> </td><td colspan=2 rowspan=2 bgcolor=#FFFF00>Dis&searr;</td><td rowspan=2 bgcolor=#FFFFFF> 4</td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.5 (0.54)</td><td bgcolor=#FFFF00>41&searr;</td><td bgcolor=#3AEE85>-31 p  &searr;</td><td bgcolor=#FFFFFF>-£0.32</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 02:00</td><td bgcolor=#FFFFAA>14.99 (16.52) </td><td bgcolor=#FFFFFF><b>15.00 (13.68)</b> </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.53 (0.58)</td><td bgcolor=#FFFF00>20&searr;</td><td bgcolor=#3AEE85>-19 p  &searr;</td><td bgcolor=#FFFFFF>-£0.64</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 02:30</td><td bgcolor=#3AEE85>13.23 (14.58) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>1.05 (1.22)</td><td bgcolor=#F18261>6&searr;</td><td bgcolor=#F18261>+11 p  &nearr;</td><td bgcolor=#FFFFFF>-£0.83</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 03:00</td><td bgcolor=#3AEE85><b>8.57 (9.45)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 rowspan=7 bgcolor=#3AEE85>Chrg&nearr;</td><td rowspan=7 bgcolor=#FFFFFF> 100</td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>1.44 (1.58)</td><td bgcolor=#F18261>4&nearr;</td><td bgcolor=#F18261>+33 p  &nearr;</td><td bgcolor=#FFFFFF>-£0.72</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 03:30</td><td bgcolor=#3AEE85><b>8.40 (9.26)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.77 (0.83)</td><td bgcolor=#FFFF00>21&nearr;</td><td bgcolor=#F18261>+26 p  &nearr;</td><td bgcolor=#FFFFFF>-£0.38</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 04:00</td><td bgcolor=#3AEE85><b>7.94 (8.75)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.82 (0.89)</td><td bgcolor=#FFFF00>37&nearr;</td><td bgcolor=#F18261>+25 p  &nearr;</td><td bgcolor=#FFFFFF>-£0.11</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 04:30</td><td bgcolor=#3AEE85><b>7.48 (8.25)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.59 (0.63)</td><td bgcolor=#3AEE85>53&nearr;</td><td bgcolor=#F18261>+22 p  &nearr;</td><td bgcolor=#FFFFFF>£0.14</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 05:00</td><td bgcolor=#3AEE85><b>9.04 (9.96)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#BCBCBC>0.05 (0.03)</td><td bgcolor=#FFFF00>0.27 (0.27)</td><td bgcolor=#3AEE85>68&nearr;</td><td bgcolor=#F18261>+24 p  &nearr;</td><td bgcolor=#FFFFFF>£0.37</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 05:30</td><td bgcolor=#3AEE85><b>8.82 (9.72)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFFF00>0.17 (0.1)&#9728;</td><td bgcolor=#AAFFAA>0.12 (0.13)</td><td bgcolor=#3AEE85>85&nearr;</td><td bgcolor=#F18261>+17 p  &nearr;</td><td bgcolor=#FFFFFF>£0.61</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 06:00</td><td bgcolor=#3AEE85><b>12.95 (14.27)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>0.35 (0.16)&#9728;</td><td bgcolor=#FFFF00>0.25 (0.28)</td><td bgcolor=#3AEE85>98&nearr;</td><td bgcolor=#FFFF00>+1 p  &nearr;</td><td bgcolor=#FFFFFF>£0.78</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 06:30</td><td bgcolor=#FFFFAA>14.86 (16.38) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr; &#8526;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>0.65 (0.21)&#9728;</td><td bgcolor=#AAFFAA>0.19 (0.22)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-6 p  &searr;</td><td bgcolor=#FFFFFF>£0.80</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 07:00</td><td bgcolor=#FFFFAA>14.97 (16.50) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr; &#8526;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>0.98 (0.28)&#9728;</td><td bgcolor=#AAFFAA>0.18 (0.19)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-11 p  &searr;</td><td bgcolor=#FFFFFF>£0.74</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 07:30</td><td bgcolor=#FFFFAA>15.72 (17.33) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr; &#8526;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>1.37 (0.39)&#9728;</td><td bgcolor=#AAFFAA>0.22 (0.25)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-16 p  &searr;</td><td bgcolor=#FFFFFF>£0.62</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 08:00</td><td bgcolor=#FFFFAA>17.44 (19.22) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>1.77 (0.52)&#9728;</td><td bgcolor=#AAFFAA>0.24 (0.26)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-21 p  &searr;</td><td bgcolor=#FFFFFF>£0.46</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 08:30</td><td bgcolor=#FFFFAA>17.20 (18.96) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>2.13 (0.65)&#9728;</td><td bgcolor=#AAFFAA>0.21 (0.23)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-27 p  &searr;</td><td bgcolor=#FFFFFF>£0.24</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 09:00</td><td bgcolor=#FFFFAA>16.32 (17.99) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>2.46 (0.79)&#9728;</td><td bgcolor=#FFFF00>0.28 (0.3)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-31 p  &searr;</td><td bgcolor=#FFFFFF>-£0.04</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 09:30</td><td bgcolor=#3AEE85><b>13.12 (14.46)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#34DBEB>HoldChrg&rarr;</td><td bgcolor=#FFFFFF> 100</td><td bgcolor=#FFAAAA>2.81 (0.94)&#9728;</td><td bgcolor=#FFFF00>0.42 (0.5)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-34 p  &searr;</td><td bgcolor=#FFFFFF>-£0.35</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 10:00</td><td bgcolor=#3AEE85>10.36 (11.42) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>3.13 (1.09)&#9728;</td><td bgcolor=#FFFF00>0.37 (0.37)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-39 p  &searr;</td><td bgcolor=#FFFFFF>-£0.69</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 10:30</td><td bgcolor=#3AEE85><b>8.38 (9.24)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#34DBEB>HoldChrg&rarr;</td><td bgcolor=#FFFFFF> 100</td><td bgcolor=#FFAAAA>3.4 (1.26)&#9728;</td><td bgcolor=#F18261>0.83 (0.95)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-36 p  &searr;</td><td bgcolor=#FFFFFF>-£1.09</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 11:00</td><td bgcolor=#3AEE85>4.65 (5.13) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>3.63 (1.38)&#9728;</td><td bgcolor=#FFFF00>0.33 (0.35)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-47 p  &searr;</td><td bgcolor=#FFFFFF>-£1.45</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 11:30</td><td bgcolor=#3AEE85>4.11 (4.53) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>3.79 (1.47)&#9728;</td><td bgcolor=#FFFF00>0.33 (0.37)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-49 p  &searr;</td><td bgcolor=#FFFFFF>-£1.93</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 12:00</td><td bgcolor=#3AEE85><b>0.02 (0.02)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 rowspan=4 bgcolor=#34DBEB>HoldChrg&rarr;</td><td rowspan=4 bgcolor=#FFFFFF> 100</td><td bgcolor=#FFAAAA>3.88 (1.51)&#9728;</td><td bgcolor=#F18261>1.29 (1.49)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-36 p  &searr;</td><td bgcolor=#FFFFFF>-£2.42</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 12:30</td><td bgcolor=#74C1FF><b>-0.22 (-0.24)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>3.91 (1.5)&#9728;</td><td bgcolor=#F18261>1.0 (1.05)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-41 p  &searr;</td><td bgcolor=#FFFFFF>-£2.79</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 13:00</td><td bgcolor=#74C1FF><b>-1.34 (-1.48)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>3.83 (1.41)&#9728;</td><td bgcolor=#F18261>0.67 (0.76)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-44 p  &searr;</td><td bgcolor=#FFFFFF>-£3.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 13:30</td><td bgcolor=#74C1FF><b>-2.21 (-2.44)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>3.64 (1.24)&#9728;</td><td bgcolor=#F18261>0.66 (0.7)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-42 p  &searr;</td><td bgcolor=#FFFFFF>-£3.65</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 14:00</td><td bgcolor=#74C1FF>-3.83 (-4.22) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>3.45 (1.06)&#9728;</td><td bgcolor=#FFFF00>0.39 (0.41)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-43 p  &searr;</td><td bgcolor=#FFFFFF>-£4.08</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 14:30</td><td bgcolor=#74C1FF><b>-3.97 (-4.38)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 rowspan=2 bgcolor=#34DBEB>HoldChrg&rarr;</td><td rowspan=2 bgcolor=#FFFFFF> 100</td><td bgcolor=#FFAAAA>3.23 (0.88)&#9728;</td><td bgcolor=#FFFF00>0.37 (0.42)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-40 p  &searr;</td><td bgcolor=#FFFFFF>-£4.52</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 15:00</td><td bgcolor=#74C1FF><b>-3.07 (-3.38)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>3.03 (0.77)&#9728;</td><td bgcolor=#FFFF00>0.4 (0.42)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-37 p  &searr;</td><td bgcolor=#FFFFFF>-£4.92</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 15:30</td><td bgcolor=#74C1FF>-2.21 (-2.44) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>2.86 (0.72)&#9728;</td><td bgcolor=#FFFF00>0.26 (0.28)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-37 p  &searr;</td><td bgcolor=#FFFFFF>-£5.30</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 16:00</td><td bgcolor=#3AEE85><b>8.98 (9.90)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 rowspan=3 bgcolor=#34DBEB>HoldChrg&rarr;</td><td rowspan=3 bgcolor=#FFFFFF> 100</td><td bgcolor=#FFAAAA>2.63 (0.62)&#9728;</td><td bgcolor=#FFFF00>0.47 (0.53)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-30 p  &searr;</td><td bgcolor=#FFFFFF>-£5.67</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 16:30</td><td bgcolor=#3AEE85><b>13.17 (14.52)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>2.34 (0.5)&#9728;</td><td bgcolor=#FFFF00>0.39 (0.44)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-27 p  &searr;</td><td bgcolor=#FFFFFF>-£5.98</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 17:00</td><td bgcolor=#3AEE85><b>12.24 (13.49)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>2.1 (0.44)&#9728;</td><td bgcolor=#F18261>0.52 (0.57)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-22 p  &searr;</td><td bgcolor=#FFFFFF>-£6.26</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 17:30</td><td bgcolor=#FFFFAA>15.86 (17.48) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>2.01 (0.45)&#9728;</td><td bgcolor=#F18261>0.9 (1.0)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-15 p  &searr;</td><td bgcolor=#FFFFFF>-£6.49</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 18:00</td><td bgcolor=#FFFFAA>18.32 (20.19) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>1.86 (0.43)&#9728;</td><td bgcolor=#FFFF00>0.44 (0.45)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-20 p  &searr;</td><td bgcolor=#FFFFFF>-£6.64</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 18:30</td><td bgcolor=#FFFFAA>20.49 (22.59) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>1.65 (0.41)&#9728;</td><td bgcolor=#FFFF00>0.29 (0.31)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-19 p  &searr;</td><td bgcolor=#FFFFFF>-£6.84</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 19:00</td><td bgcolor=#3AEE85><b>13.27 (14.63)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 rowspan=3 bgcolor=#34DBEB>HoldChrg&rarr;</td><td rowspan=3 bgcolor=#FFFFFF> 100</td><td bgcolor=#FFAAAA>1.44 (0.36)&#9728;</td><td bgcolor=#F18261>0.61 (0.69)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-11 p  &searr;</td><td bgcolor=#FFFFFF>-£7.04</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 19:30</td><td bgcolor=#3AEE85><b>14.33 (15.80)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>1.13 (0.26)&#9728;</td><td bgcolor=#FFFF00>0.33 (0.37)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-11 p  &searr;</td><td bgcolor=#FFFFFF>-£7.15</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 20:00</td><td bgcolor=#FFFFAA><b>16.12 (17.77)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#FFAAAA>0.79 (0.17)&#9728;</td><td bgcolor=#FFFF00>0.48 (0.51)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-4 p  &searr;</td><td bgcolor=#FFFFFF>-£7.27</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 20:30</td><td bgcolor=#FFFFAA>15.44 (17.02) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&rarr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#FFAAAA>0.39 (0.08)&#9728;</td><td bgcolor=#FFFF00>0.33 (0.36)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#3AEE85>-0 p  &searr;</td><td bgcolor=#FFFFFF>-£7.31</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 21:00</td><td bgcolor=#FFFFAA><b>16.50 (18.19)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 rowspan=2 bgcolor=#3AEE85>Chrg&nearr;</td><td rowspan=2 bgcolor=#FFFFFF> 100</td><td bgcolor=#BCBCBC>0.02 (0.01)</td><td bgcolor=#FFFF00>0.28 (0.32)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#FFFF00>+4 p  &nearr;</td><td bgcolor=#FFFFFF>-£7.32</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 21:30</td><td bgcolor=#FFFFAA><b>16.72 (18.43)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#BCBCBC></td><td bgcolor=#FFFF00>0.43 (0.48)</td><td bgcolor=#3AEE85>100&rarr;</td><td bgcolor=#FFFF00>+7 p  &nearr;</td><td bgcolor=#FFFFFF>-£7.27</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 22:00</td><td bgcolor=#FFFFAA>16.74 (18.45) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#FFFF00>0.38 (0.41)</td><td bgcolor=#3AEE85>100&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 22:30</td><td bgcolor=#FFFFAA>15.10 (16.64) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#FFFF00>0.47 (0.53)</td><td bgcolor=#3AEE85>97&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 23:00</td><td bgcolor=#FFFFAA><i>15.10 ?</i> (16.64) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#FFFF00>0.44 (0.48)</td><td bgcolor=#3AEE85>93&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sat 23:30</td><td bgcolor=#FFFFAA><i>15.10 ?</i> (16.64) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#FFFF00>0.45 (0.47)</td><td bgcolor=#3AEE85>90&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sun 00:00</td><td bgcolor=#FFFFAA><i>16.54 ?</i> (18.23) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.52 (0.61)</td><td bgcolor=#3AEE85>86&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sun 00:30</td><td bgcolor=#FFFFAA><i>16.54 ?</i> (18.23) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.71 (0.77)</td><td bgcolor=#3AEE85>82&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sun 01:00</td><td bgcolor=#FFFFAA><i>17.72 ?</i> (19.53) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.58 (0.65)</td><td bgcolor=#3AEE85>76&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sun 01:30</td><td bgcolor=#FFFFAA><i>18.22 ?</i> (20.08) </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 bgcolor=#FFFFFF>&searr;</td><td bgcolor=#FFFFFF> </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.57 (0.62)</td><td bgcolor=#3AEE85>72&searr;</td><td bgcolor=#FFFFFF> &rarr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sun 02:00</td><td bgcolor=#FFFFAA><b><i>14.99 ?</i> (16.52)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td colspan=2 rowspan=33 bgcolor=#3AEE85>Chrg&nearr;</td><td rowspan=33 bgcolor=#FFFFFF> 100</td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>0.6 (0.65)</td><td bgcolor=#3AEE85>67&nearr;</td><td bgcolor=#F18261>+12 p  &nearr;</td><td bgcolor=#FFFFFF>-£7.20</td></tr><tr style="color:black"><td bgcolor=#FFFFFF>Sun 02:30</td><td bgcolor=#3AEE85><b><i>13.23 ?</i> (14.58)</b> </td><td bgcolor=#FFFFFF>15.00 (13.68) </td><td bgcolor=#BCBCBC></td><td bgcolor=#F18261>1.14 (1.31)</td><td bgcolor=#3AEE85>68&nearr;</td><td bgcolor=#F18261>+18 p  &nearr;</td><td bgcolor=#FFFFFF>-£7.07</td></tr></table>
friendly_name: Plan in HTML
icon: mdi:web-box

**Comment by gcoan** [comment]
Further update: just rolled past 1am and now the first row of the table card displayed is 1:30 🤷‍♂️

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/fa3d4585-5184-40a3-bba9-a8cc739ce341)

**Comment by gcoan** [comment]
Further update:

This appears to be related to Predbat v8.0.0

First thing this morning same thing, first row missing from the table card.

Upgraded to latest predbat 8.2.4, table card now correctly displays first row

downgraded to 8.0.0, first row disappears

So maybe something obscure in the HTML (copied above) for this predbat version, probably low priority if the fix is to upgrade to newer Predbat.  I was only running an old version because that was what I had in my fork and I was testing fixes to some Predbat bugs I'd made

**Comment by pacemaker82** [comment]
yeah its because in 8.2.x trefor added a new row of metadata at the top of the table. The quick fix was for me to skip that, but the downside is anyone pre 8.2.x will have the first row ignored in the table. 

I need to do an "if" on the predbat version to support both scenarios, or detect some other way. Probably latter is better option in case trefor adds more rows of metadata before the actual table data.

**Comment by pacemaker82** [comment]
Should be fixed in [latest version 1.5.5.3](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.5.3)

**Comment by gcoan** [comment]
> Should be fixed in latest version 1.5.5.3. Its not a fancy fix but it at least will guarentee my code looks at the table of data and not his metadata. Ideally his metadata wouldnt be part of the table HTML as its not part of the table data, but alas.

1.5.5.3 works fine on both 8.0.0 and 8.2.4, thanks

Proper meta data structure is on my to-do list, but working through some other things first....
