### ISSUE TITLE
Feature Request - Expert mode price below import standard price

### ISSUE THREAD

**Issue by dandwhelan** [pacemaker82/PredBat-Table-Card#4]
I see you've added the ability to add Import / Export to one Column. Great feature. 
The Export is always 15p in my use case, so I've hidden the column. 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/79152287/d75cf056-eba1-4cfc-9c13-5d3af96109d8)

Can you separate the price after Invertor loss in brackets like the export below? 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/79152287/99de406e-59d1-4a19-a9d7-32884d24df6f)

EG The price in brackets to show instead of the export price.

Also when viewing on my mobile it takes up less screen real estate :)

**Comment by pacemaker82** [comment]
Thanks - yeah I can look into this.

**Comment by pacemaker82** [comment]
This is now in version 1.0.5

<img width="861" alt="Screenshot 2024-02-28 at 20 35 38" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/0392439c-ab0b-4512-9f4a-53e748117e6c">
