### ISSUE TITLE
Breaking Predbat change, Discharge now Export

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#43]
https://github.com/springfall2008/batpred/releases/tag/v8.7.0

**Comment by kernow** [comment]
Has anyone tried updating so wee if it breaks?

**Comment by gcoan** [comment]
@swiftrr has I believe the card works OK on 'normal' mode but doesn't on old_skool

**Comment by SwiftRR** [comment]
old_skool is fine as is friendly_states, running in v8.7.0:
<img width="675" alt="image" src="https://github.com/user-attachments/assets/322fb32b-9483-4c43-983e-ae9660cc13e9">

I guess that the only change needed is to use export/exporting for discharge/discharging.

I haven't used this card for a while but I like it. The mobile view alternative is really neat.

I now have 2 HTML views on my dashboard, one for the 'Trefor HTML card' and one for this HTML card.

Rob

**Comment by gcoan** [comment]
@SwiftRR would be useful to see what a forced discharge, now known as export, looks like in the card.  The screen shot above shows normal Eco/Idle/Demand (yuck) discharging to meet house load

I think that's the one the card won't work correctly for

**Comment by pacemaker82** [comment]
I am working on this. "discharging" doesnt necessarily mean exporting, so I need to make sure I get the logic right.

**Comment by SwiftRR** [comment]
I have tried different options with screenshots to help out.

- force discharge is still there as an entity. Many time slots aren't shown and if I select one, nothing happens.
- force export is there and shows up on both Trefor HTML and Pacemaker82 HTML with funny friendly name! But it still seems to work .....

See below with 'Trefor HTML on left.
**Force export set**
<img width="725" alt="image" src="https://github.com/user-attachments/assets/de436ab3-1f48-4b6b-8f42-ceb0c03681c8">
**Force export off**
<img width="695" alt="image" src="https://github.com/user-attachments/assets/a6b1eed3-c4c7-49f4-80bf-fb3f0b0c17b0">

Back to you .... Hope it helps.
Tell me if you want me to do more trialling.

I have looked at the code and I can sort of understand make sense of it (which is more than I can say about much of predbat code.

Rob

**Comment by pacemaker82** [comment]
So release 1.5.6 is out now to support this new terminology. I didnt see any breaking changes, but I did update the terminology for Planned and Forced Discharge to use "Export"

<img width="645" alt="Screenshot 2024-11-25 at 18 26 38" src="https://github.com/user-attachments/assets/82cbcb79-a082-4b8b-bb7a-043d2183bc34">

**Comment by gcoan** [comment]
Thanks @pacemaker82 I assume it's still backwards compatible with the old Predbat versions that use the Discharge terminology ?

**Comment by pacemaker82** [comment]
It should display “Export” on previous versions too, it won’t break
compatibility though.

**Comment by SwiftRR** [comment]
Just checked and looks OK. Works fine.
..... But shouldn't Friendly name: 'Discharging' have been changed to 'Exporting'?
<img width="569" alt="image" src="https://github.com/user-attachments/assets/67c962f6-c887-4218-b424-f4f985349dbc">

Rob

**Comment by pacemaker82** [comment]
Not in my opinion. “Discharging” is discharging battery to house, export is
exporting battery to grid.

The status is of the battery, not what your solar is doing.

That’s how I think about it anyway…. Maybe I’m wrong?

**Comment by gcoan** [comment]
> Not in my opinion. “Discharging” is discharging battery to house, export is exporting battery to grid. The status is of the battery, not what your solar is doing. That’s how I think about it anyway…. Maybe I’m wrong?

I agree

If the inverter is in Eco mode it is supplying the house load and discharging or charging depending on what the solar is doing.  Discharging is the right phrase, the battery is only discharging enough to meet house demand.

If it's a planned forced discharge then the inverter is actually set to 'Forced Export' mode and the battery will discharge at its maximum rate, again meeting the house demand but also exporting the excess.  The intent is to export, not just to discharge.

**Comment by SwiftRR** [comment]
I was referring to Trefor's 'What's changed' for v8.7.0 where I felt he was wanting to change 'discharging' to 'exporting' throughout.
But in Trefor's HTML plan, discharging to the home and exporting to grid are shown as ↘.
See also documentation: https://springfall2008.github.io/batpred/predbat-plan-card/#understanding-the-predbat-plan

But your Table card is not Trefor's plan and you use 'Friendly states' to assist understanding.
**I am happy with discharging being used 'to the house' and exporting 'to the grid'.**

In the readme for the Table Card, could the 'Friendly states' explanation for discharging be extended to:
'Discharging to home'
And an explanation for 'Forced Export' as 'Exporting to grid' be added (Export not in Friendly states section at all).
..... or something similar.

Rob

**Comment by pacemaker82** [comment]
I made some further enhancements in 1.5.6.1 out now. This was to change the "Discharge" terminology to "Export" when not using friendly text. 

<img width="751" alt="Screenshot 2024-11-27 at 10 00 33" src="https://github.com/user-attachments/assets/b590dd15-0ddb-4135-bec7-cb2c5ffcc58e">

**Comment by pacemaker82** [comment]
good point regarding the README - will get that updated.

> I was referring to Trefor's 'What's changed' for v8.7.0 where I felt he was wanting to change 'discharging' to 'exporting' throughout. But in Trefor's HTML plan, discharging to the home and exporting to grid are shown as ↘. See also documentation: https://springfall2008.github.io/batpred/predbat-plan-card/#understanding-the-predbat-plan
> 
> But your Table card is not Trefor's plan and you use 'Friendly states' to assist understanding. **I am happy with discharging being used 'to the house' and exporting 'to the grid'.**
> 
> In the readme for the Table Card, could the 'Friendly states' explanation for discharging be extended to: 'Discharging to home' And an explanation for 'Forced Export' as 'Exporting to grid' be added (Export not in Friendly states section at all). ..... or something similar.
> 
> Rob

**Comment by pacemaker82** [comment]
yeah I dont disagree with that tbh. I will have think about it - I think ↗ meaning "charging" and where Trefor has "Chrg" its actually "Import" as its a planned import from grid to charge the battery. Versus ↗ which is charge from solar.

**Comment by gcoan** [comment]
I can live with whatever it ends up being (well reserve the right to change my mind) but I do want to be able to distinguish easily between 

(1) forced (grid import) charging of the batteries / forced (grid export) discharging of the batteries 

and 

(2) PV solar charging and Eco mode battery discharging


Personally OK with Forced Charging/Forced Export for (1) and Charging/Discharging for (2)

**Comment by sammort** [comment]
I've got blank spaces in the State column when it would be only a planned export (I'm not using old-school styling). The icon shows correctly if there is import and export in the slot

<img width="412" alt="image" src="https://github.com/user-attachments/assets/838ca725-0b8e-4106-bd5e-fcd3d07eaf20">

**Comment by pacemaker82** [comment]
Ah. I’ll take a look at that. Thx

**Comment by pacemaker82** [comment]
Fixed in 1.5.6.2 - thanks for picking that up

> I've got blank spaces in the State column when it would be only a planned export (I'm not using old-school styling). The icon shows correctly if there is import and export in the slot
> 
> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/29308020/390946202-838ca725-0b8e-4106-bd5e-fcd3d07eaf20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Njk3ODYsIm5iZiI6MTczMjg2OTQ4NiwicGF0aCI6Ii8yOTMwODAyMC8zOTA5NDYyMDItODM4Y2E3MjUtMGI4ZS00MTA2LWJkNWUtZmNkM2QwN2VhZjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA4MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NmM5OWZiMzg1M2MzMmRjMjYxNjViYjc4MzU2MjFkNDBlMzJiY2U3MTI0MWMwM2RmNzJkZDkxNWJkZmJiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S4BYh5W9cgN7Kj4UodcMTz7L6RSwlAYLMjt3uGFjlk4">
