### ISSUE TITLE
Plan not updating following card upgrade

### ISSUE THREAD

**Issue by SwiftRR** [pacemaker82/PredBat-Table-Card#5]
I have tried re-downloading the card, deterring the view in my dashboard, deleting the files in www.community, restoring HA, all with no luck. The new files in www.community have date and time in the last hour.
The old card view won't go away.
I have tried in normal and export mode and I have attached screenshots (also Trefor's predbat plan) so that you can see what I can see. 
In Export mode, I expected to see the loss values shown beneath the import and export values (as in Trefor's plan). So I am still getting the really wide columns.

<img width="569" alt="Screenshot 2024-02-28 at 15 25 09" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/68816364/2e5d4d9a-e823-4de3-b0d3-b688ffdc117c">
<img width="685" alt="Screenshot 2024-02-28 at 15 28 46" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/68816364/79441306-96eb-4d27-8c51-2d36a0ea49ed">
<img width="555" alt="Screenshot 2024-02-28 at 15 30 29" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/68816364/ba803e9f-6dc7-4b8e-9ff0-2a275f473faf">

Rob

**Comment by pacemaker82** [comment]
Hi. 

The "really long" prices are still there in the most recent release when you use the HTML debug mode. If you want them stacked (import and export in the same column) you need to update the card YAML:

Remove:
`import-column`
`export-column`

Add
`import-export-column`

This will show both import and export in the same column on top of each other:
<img width="714" alt="Screenshot 2024-02-28 at 13 10 30" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/233c3cb1-5b7f-47c4-99ed-abf8a9f5369b">

**Comment by SwiftRR** [comment]
Thanks.

That works for normal and expert modes. But I was wanting 2 columns for import and export with the loss values below each time (as in Trefor's PredBat plan) which still reduces the column widths (but not as much).
Otherwise, it is easy to muddle the import and export values when they change colour.

Rob

**Comment by pacemaker82** [comment]
Yeah someone else has asked for that, I am working on it. I will try get something out tonight or tomorrow
