### ISSUE TITLE
Car Charger Text Colour

### ISSUE THREAD

**Issue by dandwhelan** [pacemaker82/PredBat-Table-Card#6]
Can you please change or add an option for the user to modify the car khw charging amount? It's rather dark.

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/79152287/a76054a8-c139-42b5-a3bd-11c75be1897e)

**Comment by pacemaker82** [comment]
oh interesting - I see it as white my side. Looks like a bug, so will fix!

**Comment by dandwhelan** [comment]
Success! we have white text. Thanks.

**Comment by pacemaker82** [comment]
marvellous
