### ISSUE TITLE
Contents issue with 1.0.6

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#8]
When checking the 1.0.6, appears that the bottom half of the plan is having an issue decoding the predbat data...

First half ok
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/6be9a749-5ecb-4267-a9cc-9b0577128717)

Bottom bit - import and then export rates messed up
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/0744ca1d-b095-4471-9355-a4bd842e1f49)

Is it the question marks for future unknown Agile rates that is messing up the parsing?
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/b5a29d3f-0205-4a79-a7f1-7165299bbc98)

**Comment by pacemaker82** [comment]
Ah, I forgot to handle the italic for the "predicted" costs when stacking the debug pills. Thanks - will fix that

**Comment by gcoan** [comment]
Thanks for fixing quickly, new version works fine
