### ISSUE TITLE
Card doesn't display rate over-ride power up prices correctly

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#9]
Power up event today, I set a import rate override of zero rate:

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/33d787bd-5362-462d-b63b-5b132e66fec7)

Card doesn't parse the predbat html correctly:
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/c1e0916c-b810-411a-9464-d621efab6933)

**Comment by pacemaker82** [comment]
Yeah this was raised on another thread. Have fixed. Will push release shortly.

**Comment by pacemaker82** [comment]
Pushed [version 1.0.9](https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.0.9) to fix. Let me know how you get on (I am testing it a bit blind as dont get them in my area)

**Comment by pacemaker82** [comment]
Whats the ± pricing you got there, that also is breaking - never seen that before either.

**Comment by PianSom** [comment]
To steal Geoffrey's thunder (he is largely writing the docs!) - https://springfall2008.github.io/batpred/predbat-plan-card/#understanding-the-predbat-plan

There should be a Savings Session arriving for later today shortly, so another chance to check functionality.

**Comment by gcoan** [comment]
Power up prices are working OK now with 1.0.9, thanks

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/ac880873-0099-4f1f-bebd-879e43558d1c)

As @PianSom says, RTFM for codes used in the predbat plan!!

**Comment by gcoan** [comment]
Hadn't noticed, but +/- rate offset prices don't display either.
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/0e6a4e16-fcfc-4584-89ab-45e13acf5518)

I have a rate offset of -5p set for the peak period so that Predbat doesn't discharge then, to keep my average peak period export at zero for future DFS sessions

**Comment by pacemaker82** [comment]
Should be fixed in latest release https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.0.10

**Comment by gcoan** [comment]
1.0.11 works fine

It displays the +/- symbol for the relative rate reduction and the scales symbol for the norddata tomorrow estimate,  but it doesn't show the = for the rate override - which TBH I am quite happy with.  Seeing the = doesn't add anything, I know there's a rate override, I set it...

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/2d3958ee-5d5f-4fa2-8c3e-dee00a700276)
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/a208c95f-7286-49df-81a9-6ff38cb3a4d4)
